// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2fmgke-FCQpTFtf1u6MPEwxiLvJ9p5fs',
    appId: '1:760600070684:web:38da2c447b6040a850add9',
    messagingSenderId: '760600070684',
    projectId: 'tinder-a928a',
    authDomain: 'tinder-a928a.firebaseapp.com',
    storageBucket: 'tinder-a928a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZRm2lJANJyhRtgUC-zhscqhF1wnpdhig',
    appId: '1:760600070684:android:826549c4b0abec1b50add9',
    messagingSenderId: '760600070684',
    projectId: 'tinder-a928a',
    storageBucket: 'tinder-a928a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Y2h-6xN6PFkdVDOk9BT9ryXVOhiTlW8',
    appId: '1:760600070684:ios:6e36ac27ab7eaf8550add9',
    messagingSenderId: '760600070684',
    projectId: 'tinder-a928a',
    storageBucket: 'tinder-a928a.appspot.com',
    iosBundleId: 'com.example.tinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Y2h-6xN6PFkdVDOk9BT9ryXVOhiTlW8',
    appId: '1:760600070684:ios:e4ee9c46c0fc694d50add9',
    messagingSenderId: '760600070684',
    projectId: 'tinder-a928a',
    storageBucket: 'tinder-a928a.appspot.com',
    iosBundleId: 'com.example.tinder.RunnerTests',
  );
}
